### ISSUE TITLE
Panel font smoothing doesn't match font smoothing used in the rest of the Notepad++ UI

### ISSUE THREAD

**Issue by tomasz1986** [vinsworldcom/nppChangedLines#10]
I'm not sure what the exact problem is, but the font used inside the panel doesn't seem to use the same smoothing method as the rest of the UI. Not an expert here, but it looks as if it used grayscale antialiasing instead of ClearType.

You can see the difference below.

![image](https://user-images.githubusercontent.com/5626656/164970743-859bd155-2a02-4fd8-9aec-d661f4ab7a91.png)

**Comment by vinsworldcom** [comment]
@tomasz1986 please try the [artifact for your architecture](https://github.com/vinsworldcom/nppChangedLines/actions/runs/2270761431) of the latest build and let me know if that is better.  The recommendation from M$ is to use "MS Shell Dlg" as the `FONT` in resource files instead of what I was using ("MS Sans Serif").

Cheers.

**Comment by tomasz1986** [comment]
Thank you for a quick fix! The fonts in the artifact seem to have the same look as the rest of the GUI.
