### ISSUE TITLE
Markers aren't updated in inactive files during SaveAll

### ISSUE THREAD

**Issue by sasumner** [vinsworldcom/nppChangedLines#6]
Steps to reproduce:

1. Start with two modified file tabs.  Have one of these be the currently-active file.
2. Press the SaveAll button on the Notepad++ toolbar (or otherwise do a "Save All").
3. Observe that change marks in active file change color to indicated the "saved" status.
4. Switch to the other file that was initially modified but is now saved.
5. Observe that its change marks still indicate an "unsaved" status.

**Comment by vinsworldcom** [comment]
Seems to be a bit harder than I thought.  I thought I could just catch NPPN_FILEBEFORESAVE  like I do for SCN_SAVEPOINTREACHED and that does the convertChangeToSave() call.  But I may need to pull more info from the NPPN_FILEBEFORESAVE notification - like the BufferID and somehow feed that to convertChangeToSave().

Perhaps looking at the NPP code for "Save All" to see what notifications are triggered may help me.

Cheers.

**Comment by vinsworldcom** [comment]
Seems Notepad++ does Save All [by looping through BufferIDs and saving each file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/013305f306039998c0ba8a85c03238843879b6cf/PowerEditor/src/NppIO.cpp#L1610).  While I get NPPN_FILESAVED notifications (can easily switch from the current use of SCI_SAVEPOINTREACHD) for each and that notification contains the BufferID, I'm not sure how to activate a tab by BufferID since I issue [SendMessage() SCI_ commands to the current tab](https://github.com/vinsworldcom/nppChangedLines/blob/9367e9691ec4d2f745501a75e4416d37abf59748/PluginDefinition.cpp#L525) to convert changed to saved.  I can pass that sub the BufferID, but then how to activate that BufferID?  Something more elegant than using:

NPPM_GETFULLPATHFROMBUFFERID
NPPM_DOOPEN

It's quite possible I'm missing something obvious.

Cheers.

**Comment by sasumner** [comment]
How about `NPPM_SWITCHTOFILE` ?

**Comment by vinsworldcom** [comment]
I was missing something obvious as assumed.  I'll give it a shot later this week.  Thanks!

**Comment by vinsworldcom** [comment]
Sort of works:

ChangedLines.cpp
```
        case NPPN_FILESAVED:
         {
            convertChangeToSave( notifyCode->nmhdr.idFrom );
         }
         break;
```

PluginDefinition.cpp
```
void convertChangeToSave( uptr_t bufferId )
 {
     HWND hCurScintilla = getCurScintilla();

    TCHAR path[MAX_PATH];
    SendMessage( hCurScintilla, NPPM_GETFULLPATHFROMBUFFERID, bufferId, ( LPARAM )path );
    SendMessage( hCurScintilla, NPPM_SWITCHTOFILE, 0, ( LPARAM )path );

[...]
```

With that, it "iterates" over all the "Save All" file BufferIDs from Notepad++ NPPN_FILESAVED notification, but only if in the first Scintilla view.  If files are in the second view, I need to figure some logic to query the second view.

I think the NPPM_GETFULLPATHFROMBUFFERID returns -1 if the buffer doesn't exist, so maybe a check there for -1 before the call to NPPM_SWITCHTOFILE and if the return is -1, then get the other Scintilla view handle and try again and it not -1 this time, then do the NPPM_SWITCHTOFILE.

The other thing I noticed was that it made the text in the current Window really small which switched back to normal size when I switched tabs away then back again.  That was weird.

Cheers.

**Comment by vinsworldcom** [comment]
Notepad++ has native [Scintilla Change History](https://www.scintilla.org/ScintillaDoc.html#ChangeHistory) now so this plugin is pivoting to be just a customizer of that feature.  This save issue is now related to Scintilla / Notepad++ implementation.  Closing.
